/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ERC1616, ERC1616Interface } from "../ERC1616";

const _abi = [
  {
    inputs: [],
    name: "countAttributeTypes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getAttributeTypeID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "attributeTypeID",
        type: "uint256",
      },
    ],
    name: "getAttributeValue",
    outputs: [
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "attributeTypeID",
        type: "uint256",
      },
    ],
    name: "hasAttribute",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ERC1616__factory {
  static readonly abi = _abi;
  static createInterface(): ERC1616Interface {
    return new utils.Interface(_abi) as ERC1616Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1616 {
    return new Contract(address, _abi, signerOrProvider) as ERC1616;
  }
}
