/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ERC1616Interface extends utils.Interface {
  contractName: "ERC1616";
  functions: {
    "countAttributeTypes()": FunctionFragment;
    "getAttributeTypeID(uint256)": FunctionFragment;
    "getAttributeValue(address,uint256)": FunctionFragment;
    "hasAttribute(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "countAttributeTypes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAttributeTypeID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttributeValue",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAttribute",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "countAttributeTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttributeTypeID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttributeValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAttribute",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ERC1616 extends BaseContract {
  contractName: "ERC1616";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC1616Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    countAttributeTypes(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAttributeTypeID(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAttributeValue(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber]]>;

    hasAttribute(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  countAttributeTypes(overrides?: CallOverrides): Promise<BigNumber>;

  getAttributeTypeID(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAttributeValue(
    account: string,
    attributeTypeID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  hasAttribute(
    account: string,
    attributeTypeID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    countAttributeTypes(overrides?: CallOverrides): Promise<BigNumber>;

    getAttributeTypeID(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAttributeValue(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    hasAttribute(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    countAttributeTypes(overrides?: CallOverrides): Promise<BigNumber>;

    getAttributeTypeID(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAttributeValue(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasAttribute(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    countAttributeTypes(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAttributeTypeID(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAttributeValue(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasAttribute(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
