/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RegistryInterface extends utils.Interface {
  contractName: "Registry";
  functions: {
    "addCommodityValue(uint256)": FunctionFragment;
    "countAttributeTypes()": FunctionFragment;
    "getAttributeTypeID(uint256)": FunctionFragment;
    "getAttributeValue(address,uint256)": FunctionFragment;
    "hasAttribute(address,uint256)": FunctionFragment;
    "updateCommodityValue(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addCommodityValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "countAttributeTypes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAttributeTypeID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttributeValue",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAttribute",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCommodityValue",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCommodityValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "countAttributeTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttributeTypeID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttributeValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAttribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCommodityValue",
    data: BytesLike
  ): Result;

  events: {
    "SenderAddress(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SenderAddress"): EventFragment;
}

export type SenderAddressEvent = TypedEvent<[string], { senderAddr: string }>;

export type SenderAddressEventFilter = TypedEventFilter<SenderAddressEvent>;

export interface Registry extends BaseContract {
  contractName: "Registry";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addCommodityValue(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    countAttributeTypes(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAttributeTypeID(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAttributeValue(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber]]>;

    hasAttribute(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    updateCommodityValue(
      newValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addCommodityValue(
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  countAttributeTypes(overrides?: CallOverrides): Promise<BigNumber>;

  getAttributeTypeID(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAttributeValue(
    account: string,
    attributeTypeID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  hasAttribute(
    account: string,
    attributeTypeID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  updateCommodityValue(
    newValue: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addCommodityValue(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    countAttributeTypes(overrides?: CallOverrides): Promise<BigNumber>;

    getAttributeTypeID(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAttributeValue(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    hasAttribute(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateCommodityValue(
      newValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SenderAddress(address)"(senderAddr?: null): SenderAddressEventFilter;
    SenderAddress(senderAddr?: null): SenderAddressEventFilter;
  };

  estimateGas: {
    addCommodityValue(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    countAttributeTypes(overrides?: CallOverrides): Promise<BigNumber>;

    getAttributeTypeID(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAttributeValue(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasAttribute(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateCommodityValue(
      newValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addCommodityValue(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    countAttributeTypes(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAttributeTypeID(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAttributeValue(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasAttribute(
      account: string,
      attributeTypeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateCommodityValue(
      newValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
